namespace NetGL.WindowAPI
{
    public enum Key
    {
        Left                = 0x01,
        Right               = 0x02,
        Cancel              = 0x03,
        Middle              = 0x04,
        XButton1            = 0x05,
        XButton2            = 0x06,

        Backspace           = 0x08,
        Tab                 = 0x09,

        Clear               = 0x0C,
        Enter               = 0x0D,

        Shift               = 0x10,
        Control             = 0x11,
        Alt                 = 0x12,
        Pause               = 0x13,
        CapsLock            = 0x14,

        Hangul              = 0x15,
        IMEOn               = 0x16,
        Junja               = 0x17,
        Final               = 0x18,
        Hanja               = 0x19,
        OmeOff              = 0x1A,
        Escape              = 0x1B,
        IMEConvert          = 0x1C,
        IMENonConvert       = 0x1D,
        IMEAccept           = 0x1E,
        IMEModeChange       = 0x1F,

        Space               = 0x20,

        PageUp              = 0x21,
        PageDown            = 0x22,
        End                 = 0x23,
        Home                = 0x24,

        ArrowLeft           = 0x25,
        ArrowUp             = 0x26,
        ArrowRight          = 0x27,
        Arrowdown           = 0x28,

        Select              = 0x29,
        Print               = 0x2A,
        Execute             = 0x2B,
        PrintScreen         = 0x2C,
        Insert              = 0x2D,
        Delete              = 0x2E,
        Help                = 0x2F,

        D0                  = 0x30,
        D1, D2, D3, D4, D5, D6, D7, D8, D9,

        A                   = 0x41,
        B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z,

        LeftWindows         = 0x5B,
        RightWindows        = 0x5C,
        Apps                = 0x5D,
        Sleep               = 0x5F,
        Num0                = 0x60,
        Num1, Num2, Num3, Num4, Num5, Num6, Num7, Num8, Num9,
        NumMultiply, NumAdd, NumSeparator, NumSubtract, NumDecimal, NumDivide,

        F1                  = 0x70, 
        F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, F12, F13, F14, F15, F16, F17, F18, F19, F20, F21, F22, F23, F24,

        NumLock             = 0x90,
        ScrollLock          = 0x91,
        LeftShift           = 0xA0,
        RightShift          = 0xA1,
        LeftControl         = 0xA2,
        RightControl        = 0xA3,
        LeftAlt             = 0xA4,
        RightAlt            = 0xA5,

        BrowserBack         = 0xA6,
        BrowserForward      = 0xA7,
        BrowserRefresh      = 0xA8,
        BrowserStop         = 0xA9,
        BrowserSearch       = 0xAA,
        BrowserFavourites   = 0xAB,
        Browserhome         = 0xAB,

        VolumeMute          = 0xAD,
        VolumeDown          = 0xAE,
        VolumeUp            = 0xAF,

        MediaNext           = 0xB0,
        MediaPrevious       = 0xB1,
        MediaStop           = 0xB2,
        MediaPlay           = 0xB3,

        LaunchMail          = 0xB4,
        LaunchMediaSelect   = 0xB5,
        LaunchApp1          = 0xB6,
        LaunchApp2          = 0xB7,

        OemSemicolon        = 0xBA,
        OemColon            = 0xBA,
        OemPlus             = 0xBB,
        OemEquals           = 0xBB,
        OemComma            = 0xBC,
        OemLessThan         = 0xBC,
        OemPeriod           = 0xBD,
        OemBiggerThan       = 0xBD,
        OemSlash            = 0xBE,
        OemQuestion         = 0xBE,
        OemTidle            = 0xBF,
        OemApostrophe       = 0xC0,
        OemOpenBrackets     = 0xC0,
        OemBackslash        = 0xDC,
        OemPipe             = 0xDC,
        OemCloseBrackets    = 0xDD,
        OemQuote            = 0xDE,
        OemQuotes           = 0xDE,
        Oem8                = 0xDF,
        OemSecondPipe       = 0xE2,
        OemSecondBackslash  = 0xE2,
        ProcessKey          = 0xE5,
        Packet              = 0xE7,
        Attn                = 0xF6,
        CrSel               = 0xF7,
        ExSel               = 0xF8,
        EraseEOF            = 0xF9,
        Play                = 0xFA,
        Zoom                = 0xFB,
        NoName              = 0xFC,
        PA1                 = 0xFD,
        OemClear            = 0xFE,

        None                = 0x00
    }
}
